### ISSUE TITLE
Ubuntu Attribute Model

### ISSUE THREAD

**Issue by kimwongyuda** [microsoft/clarification-qgen-globalinfo#1]
When you train attribute model for ubuntu dataset, is the input (context, question)? and is the output (0 or 1)?
Otherwise, is the input only question?

If the first case is right, when decoding time, does attribute model has context as part of the input?

**Comment by majumderb** [comment]
You are correct. The input is (context, question) and output is (0 or 1). While decoding, you should use context as part of the input.

**Comment by kimwongyuda** [comment]
thanks!
